// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/entity/post/option.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryOption int32

const (
	QueryOption_Undefined      QueryOption = 0
	QueryOption_TitleOrContent QueryOption = 1
	QueryOption_Title          QueryOption = 2
	QueryOption_Content        QueryOption = 3
	QueryOption_Writer         QueryOption = 4
	QueryOption_Comment        QueryOption = 5
)

// Enum value maps for QueryOption.
var (
	QueryOption_name = map[int32]string{
		0: "Undefined",
		1: "TitleOrContent",
		2: "Title",
		3: "Content",
		4: "Writer",
		5: "Comment",
	}
	QueryOption_value = map[string]int32{
		"Undefined":      0,
		"TitleOrContent": 1,
		"Title":          2,
		"Content":        3,
		"Writer":         4,
		"Comment":        5,
	}
)

func (x QueryOption) Enum() *QueryOption {
	p := new(QueryOption)
	*p = x
	return p
}

func (x QueryOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_post_option_proto_enumTypes[0].Descriptor()
}

func (QueryOption) Type() protoreflect.EnumType {
	return &file_proto_entity_post_option_proto_enumTypes[0]
}

func (x QueryOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryOption.Descriptor instead.
func (QueryOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_post_option_proto_rawDescGZIP(), []int{0}
}

type ClassificationOption int32

const (
	ClassificationOption_All     ClassificationOption = 0
	ClassificationOption_Popular ClassificationOption = 1
	ClassificationOption_Notice  ClassificationOption = 2
)

// Enum value maps for ClassificationOption.
var (
	ClassificationOption_name = map[int32]string{
		0: "All",
		1: "Popular",
		2: "Notice",
	}
	ClassificationOption_value = map[string]int32{
		"All":     0,
		"Popular": 1,
		"Notice":  2,
	}
)

func (x ClassificationOption) Enum() *ClassificationOption {
	p := new(ClassificationOption)
	*p = x
	return p
}

func (x ClassificationOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClassificationOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_post_option_proto_enumTypes[1].Descriptor()
}

func (ClassificationOption) Type() protoreflect.EnumType {
	return &file_proto_entity_post_option_proto_enumTypes[1]
}

func (x ClassificationOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClassificationOption.Descriptor instead.
func (ClassificationOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_post_option_proto_rawDescGZIP(), []int{1}
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryOption          QueryOption          `protobuf:"varint,1,opt,name=query_option,json=queryOption,proto3,enum=v2.entity.post.QueryOption" json:"query_option,omitempty"`
	ClassificationOption ClassificationOption `protobuf:"varint,2,opt,name=classification_option,json=classificationOption,proto3,enum=v2.entity.post.ClassificationOption" json:"classification_option,omitempty"`
	Query                string               `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Tags                 []string             `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entity_post_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_post_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_proto_entity_post_option_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetQueryOption() QueryOption {
	if x != nil {
		return x.QueryOption
	}
	return QueryOption_Undefined
}

func (x *Option) GetClassificationOption() ClassificationOption {
	if x != nil {
		return x.ClassificationOption
	}
	return ClassificationOption_All
}

func (x *Option) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Option) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_entity_post_option_proto protoreflect.FileDescriptor

var file_proto_entity_post_option_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70,
	0x6f, 0x73, 0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x22, 0xcf, 0x01, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0c, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f,
	0x73, 0x74, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x15,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x76, 0x32,
	0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x14, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x2a, 0x62, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x4f, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x2a, 0x39, 0x0a, 0x15, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x10,
	0x02, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x74, 0x63, 0x30, 0x33, 0x30, 0x31, 0x32, 0x2f, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_entity_post_option_proto_rawDescOnce sync.Once
	file_proto_entity_post_option_proto_rawDescData = file_proto_entity_post_option_proto_rawDesc
)

func file_proto_entity_post_option_proto_rawDescGZIP() []byte {
	file_proto_entity_post_option_proto_rawDescOnce.Do(func() {
		file_proto_entity_post_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_entity_post_option_proto_rawDescData)
	})
	return file_proto_entity_post_option_proto_rawDescData
}

var file_proto_entity_post_option_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_entity_post_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_entity_post_option_proto_goTypes = []interface{}{
	(QueryOption)(0),          // 0: v2.entity.post.query_option
	(ClassificationOption)(0), // 1: v2.entity.post.classification_option
	(*Option)(nil),            // 2: v2.entity.post.option
}
var file_proto_entity_post_option_proto_depIdxs = []int32{
	0, // 0: v2.entity.post.option.query_option:type_name -> v2.entity.post.query_option
	1, // 1: v2.entity.post.option.classification_option:type_name -> v2.entity.post.classification_option
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_entity_post_option_proto_init() }
func file_proto_entity_post_option_proto_init() {
	if File_proto_entity_post_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_entity_post_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_entity_post_option_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_entity_post_option_proto_goTypes,
		DependencyIndexes: file_proto_entity_post_option_proto_depIdxs,
		EnumInfos:         file_proto_entity_post_option_proto_enumTypes,
		MessageInfos:      file_proto_entity_post_option_proto_msgTypes,
	}.Build()
	File_proto_entity_post_option_proto = out.File
	file_proto_entity_post_option_proto_rawDesc = nil
	file_proto_entity_post_option_proto_goTypes = nil
	file_proto_entity_post_option_proto_depIdxs = nil
}
