// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/entity/post/option.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchOption int32

const (
	SearchOption_Undefined       SearchOption = 0
	SearchOption_TitleAndContent SearchOption = 1
	SearchOption_Title           SearchOption = 2
	SearchOption_Content         SearchOption = 3
	SearchOption_Writer          SearchOption = 4
	SearchOption_Comment         SearchOption = 5
)

// Enum value maps for SearchOption.
var (
	SearchOption_name = map[int32]string{
		0: "Undefined",
		1: "TitleAndContent",
		2: "Title",
		3: "Content",
		4: "Writer",
		5: "Comment",
	}
	SearchOption_value = map[string]int32{
		"Undefined":       0,
		"TitleAndContent": 1,
		"Title":           2,
		"Content":         3,
		"Writer":          4,
		"Comment":         5,
	}
)

func (x SearchOption) Enum() *SearchOption {
	p := new(SearchOption)
	*p = x
	return p
}

func (x SearchOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_post_option_proto_enumTypes[0].Descriptor()
}

func (SearchOption) Type() protoreflect.EnumType {
	return &file_proto_entity_post_option_proto_enumTypes[0]
}

func (x SearchOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOption.Descriptor instead.
func (SearchOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_post_option_proto_rawDescGZIP(), []int{0}
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchOption SearchOption `protobuf:"varint,1,opt,name=search_option,json=searchOption,proto3,enum=v2.entity.post.SearchOption" json:"search_option,omitempty"`
	SearchQuery  string       `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	Tags         []string     `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entity_post_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_post_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_proto_entity_post_option_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetSearchOption() SearchOption {
	if x != nil {
		return x.SearchOption
	}
	return SearchOption_Undefined
}

func (x *Option) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *Option) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_entity_post_option_proto protoreflect.FileDescriptor

var file_proto_entity_post_option_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70,
	0x6f, 0x73, 0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x22, 0x83, 0x01, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0d, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x6f, 0x73, 0x74, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x2a, 0x64, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x41,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x74, 0x63, 0x30, 0x33,
	0x30, 0x31, 0x32, 0x2f, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_entity_post_option_proto_rawDescOnce sync.Once
	file_proto_entity_post_option_proto_rawDescData = file_proto_entity_post_option_proto_rawDesc
)

func file_proto_entity_post_option_proto_rawDescGZIP() []byte {
	file_proto_entity_post_option_proto_rawDescOnce.Do(func() {
		file_proto_entity_post_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_entity_post_option_proto_rawDescData)
	})
	return file_proto_entity_post_option_proto_rawDescData
}

var file_proto_entity_post_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_entity_post_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_entity_post_option_proto_goTypes = []interface{}{
	(SearchOption)(0), // 0: v2.entity.post.search_option
	(*Option)(nil),    // 1: v2.entity.post.option
}
var file_proto_entity_post_option_proto_depIdxs = []int32{
	0, // 0: v2.entity.post.option.search_option:type_name -> v2.entity.post.search_option
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_entity_post_option_proto_init() }
func file_proto_entity_post_option_proto_init() {
	if File_proto_entity_post_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_entity_post_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_entity_post_option_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_entity_post_option_proto_goTypes,
		DependencyIndexes: file_proto_entity_post_option_proto_depIdxs,
		EnumInfos:         file_proto_entity_post_option_proto_enumTypes,
		MessageInfos:      file_proto_entity_post_option_proto_msgTypes,
	}.Build()
	File_proto_entity_post_option_proto = out.File
	file_proto_entity_post_option_proto_rawDesc = nil
	file_proto_entity_post_option_proto_goTypes = nil
	file_proto_entity_post_option_proto_depIdxs = nil
}
