// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/dtc03012/me/db/entity"
	mock "github.com/stretchr/testify/mock"

	option "github.com/dtc03012/me/db/option"

	sqlx "github.com/jmoiron/sqlx"
)

// Post is an autogenerated mock type for the Post type
type Post struct {
	mock.Mock
}

// CheckPostPassword provides a mock function with given fields: ctx, tx, pid, password
func (_m *Post) CheckPostPassword(ctx context.Context, tx *sqlx.Tx, pid int32, password string) (bool, error) {
	ret := _m.Called(ctx, tx, pid, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, string) bool); ok {
		r0 = rf(ctx, tx, pid, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32, string) error); ok {
		r1 = rf(ctx, tx, pid, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckUserLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *Post) CheckUserLike(ctx context.Context, tx *sqlx.Tx, pid int32, uuid string) (bool, error) {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, string) bool); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32, string) error); ok {
		r1 = rf(ctx, tx, pid, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBulkTag provides a mock function with given fields: ctx, tx, pid
func (_m *Post) DeleteBulkTag(ctx context.Context, tx *sqlx.Tx, pid int32) error {
	ret := _m.Called(ctx, tx, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, tx, postId, commentId
func (_m *Post) DeleteComment(ctx context.Context, tx *sqlx.Tx, postId int, commentId int) error {
	ret := _m.Called(ctx, tx, postId, commentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, int) error); ok {
		r0 = rf(ctx, tx, postId, commentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *Post) DeleteLike(ctx context.Context, tx *sqlx.Tx, pid int32, uuid string) error {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, string) error); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: ctx, tx, pid
func (_m *Post) DeletePost(ctx context.Context, tx *sqlx.Tx, pid int32) error {
	ret := _m.Called(ctx, tx, pid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBulkComment provides a mock function with given fields: ctx, tx, opt
func (_m *Post) GetBulkComment(ctx context.Context, tx *sqlx.Tx, opt *option.CommentOption) ([]*entity.Comment, error) {
	ret := _m.Called(ctx, tx, opt)

	var r0 []*entity.Comment
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *option.CommentOption) []*entity.Comment); ok {
		r0 = rf(ctx, tx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *option.CommentOption) error); ok {
		r1 = rf(ctx, tx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBulkPost provides a mock function with given fields: ctx, tx, opt
func (_m *Post) GetBulkPost(ctx context.Context, tx *sqlx.Tx, opt *option.PostOption) ([]*entity.Post, error) {
	ret := _m.Called(ctx, tx, opt)

	var r0 []*entity.Post
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *option.PostOption) []*entity.Post); ok {
		r0 = rf(ctx, tx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *option.PostOption) error); ok {
		r1 = rf(ctx, tx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBulkTag provides a mock function with given fields: ctx, tx, pid
func (_m *Post) GetBulkTag(ctx context.Context, tx *sqlx.Tx, pid int32) ([]string, error) {
	ret := _m.Called(ctx, tx, pid)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) []string); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r1 = rf(ctx, tx, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPost provides a mock function with given fields: ctx, tx, pid
func (_m *Post) GetPost(ctx context.Context, tx *sqlx.Tx, pid int32) (*entity.Post, error) {
	ret := _m.Called(ctx, tx, pid)

	var r0 *entity.Post
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) *entity.Post); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r1 = rf(ctx, tx, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalCommentCount provides a mock function with given fields: ctx, tx, pid
func (_m *Post) GetTotalCommentCount(ctx context.Context, tx *sqlx.Tx, pid int32) (int, error) {
	ret := _m.Called(ctx, tx, pid)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) int); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r1 = rf(ctx, tx, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPostCount provides a mock function with given fields: ctx, tx
func (_m *Post) GetTotalPostCount(ctx context.Context, tx *sqlx.Tx) (int, error) {
	ret := _m.Called(ctx, tx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) int); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetViews provides a mock function with given fields: ctx, tx, pid
func (_m *Post) GetViews(ctx context.Context, tx *sqlx.Tx, pid int32) (int, error) {
	ret := _m.Called(ctx, tx, pid)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32) int); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int32) error); ok {
		r1 = rf(ctx, tx, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertBulkTag provides a mock function with given fields: ctx, tx, pid, tags
func (_m *Post) InsertBulkTag(ctx context.Context, tx *sqlx.Tx, pid int32, tags []string) error {
	ret := _m.Called(ctx, tx, pid, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, []string) error); ok {
		r0 = rf(ctx, tx, pid, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertComment provides a mock function with given fields: ctx, tx, comment
func (_m *Post) InsertComment(ctx context.Context, tx *sqlx.Tx, comment *entity.Comment) error {
	ret := _m.Called(ctx, tx, comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *entity.Comment) error); ok {
		r0 = rf(ctx, tx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *Post) InsertLike(ctx context.Context, tx *sqlx.Tx, pid int32, uuid string) error {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, string) error); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPost provides a mock function with given fields: ctx, tx, post
func (_m *Post) InsertPost(ctx context.Context, tx *sqlx.Tx, post *entity.Post) (int, error) {
	ret := _m.Called(ctx, tx, post)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *entity.Post) int); ok {
		r0 = rf(ctx, tx, post)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *entity.Post) error); ok {
		r1 = rf(ctx, tx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertViews provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *Post) InsertViews(ctx context.Context, tx *sqlx.Tx, pid int32, uuid string) error {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int32, string) error); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePost provides a mock function with given fields: ctx, tx, post
func (_m *Post) UpdatePost(ctx context.Context, tx *sqlx.Tx, post *entity.Post) error {
	ret := _m.Called(ctx, tx, post)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *entity.Post) error); ok {
		r0 = rf(ctx, tx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPost interface {
	mock.TestingT
	Cleanup(func())
}

// NewPost creates a new instance of Post. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPost(t mockConstructorTestingTNewPost) *Post {
	mock := &Post{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
