// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/service/message/post.proto

package message

import (
	post "github.com/dtc03012/me/protobuf/proto/entity/post"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *post.Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadPostRequest) Reset() {
	*x = UploadPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostRequest) ProtoMessage() {}

func (x *UploadPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostRequest.ProtoReflect.Descriptor instead.
func (*UploadPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{0}
}

func (x *UploadPostRequest) GetData() *post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadPostResponse) Reset() {
	*x = UploadPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostResponse) ProtoMessage() {}

func (x *UploadPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostResponse.ProtoReflect.Descriptor instead.
func (*UploadPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{1}
}

type FetchPostListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row  int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FetchPostListRequest) Reset() {
	*x = FetchPostListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostListRequest) ProtoMessage() {}

func (x *FetchPostListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostListRequest.ProtoReflect.Descriptor instead.
func (*FetchPostListRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{2}
}

func (x *FetchPostListRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *FetchPostListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FetchPostListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data           []*post.Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalPostCount int32        `protobuf:"varint,2,opt,name=totalPostCount,proto3" json:"totalPostCount,omitempty"`
}

func (x *FetchPostListResponse) Reset() {
	*x = FetchPostListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostListResponse) ProtoMessage() {}

func (x *FetchPostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostListResponse.ProtoReflect.Descriptor instead.
func (*FetchPostListResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{3}
}

func (x *FetchPostListResponse) GetData() []*post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FetchPostListResponse) GetTotalPostCount() int32 {
	if x != nil {
		return x.TotalPostCount
	}
	return 0
}

type FetchPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchPostRequest) Reset() {
	*x = FetchPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostRequest) ProtoMessage() {}

func (x *FetchPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostRequest.ProtoReflect.Descriptor instead.
func (*FetchPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{4}
}

func (x *FetchPostRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FetchPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *post.Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchPostResponse) Reset() {
	*x = FetchPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostResponse) ProtoMessage() {}

func (x *FetchPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostResponse.ProtoReflect.Descriptor instead.
func (*FetchPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{5}
}

func (x *FetchPostResponse) GetData() *post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type IncrementViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *IncrementViewRequest) Reset() {
	*x = IncrementViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewRequest) ProtoMessage() {}

func (x *IncrementViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewRequest.ProtoReflect.Descriptor instead.
func (*IncrementViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{6}
}

func (x *IncrementViewRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncrementViewRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type IncrementViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncrementViewResponse) Reset() {
	*x = IncrementViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewResponse) ProtoMessage() {}

func (x *IncrementViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewResponse.ProtoReflect.Descriptor instead.
func (*IncrementViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{7}
}

type LeaveCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment *post.Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *LeaveCommentRequest) Reset() {
	*x = LeaveCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommentRequest) ProtoMessage() {}

func (x *LeaveCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommentRequest.ProtoReflect.Descriptor instead.
func (*LeaveCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveCommentRequest) GetComment() *post.Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type LeaveCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveCommentResponse) Reset() {
	*x = LeaveCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommentResponse) ProtoMessage() {}

func (x *LeaveCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommentResponse.ProtoReflect.Descriptor instead.
func (*LeaveCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{9}
}

type FetchCommentListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Row    int32 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Size   int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FetchCommentListRequest) Reset() {
	*x = FetchCommentListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchCommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentListRequest) ProtoMessage() {}

func (x *FetchCommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentListRequest.ProtoReflect.Descriptor instead.
func (*FetchCommentListRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{10}
}

func (x *FetchCommentListRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FetchCommentListRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *FetchCommentListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FetchCommentListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentList       []*post.Comment `protobuf:"bytes,1,rep,name=comment_list,json=commentList,proto3" json:"comment_list,omitempty"`
	TotalCommentCount int32           `protobuf:"varint,2,opt,name=totalCommentCount,proto3" json:"totalCommentCount,omitempty"`
}

func (x *FetchCommentListResponse) Reset() {
	*x = FetchCommentListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchCommentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommentListResponse) ProtoMessage() {}

func (x *FetchCommentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommentListResponse.ProtoReflect.Descriptor instead.
func (*FetchCommentListResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{11}
}

func (x *FetchCommentListResponse) GetCommentList() []*post.Comment {
	if x != nil {
		return x.CommentList
	}
	return nil
}

func (x *FetchCommentListResponse) GetTotalCommentCount() int32 {
	if x != nil {
		return x.TotalCommentCount
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    int32 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId int32 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCommentRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{13}
}

type SearchPostListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option *post.Option `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Row    int32        `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Size   int32        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SearchPostListRequest) Reset() {
	*x = SearchPostListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPostListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostListRequest) ProtoMessage() {}

func (x *SearchPostListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostListRequest.ProtoReflect.Descriptor instead.
func (*SearchPostListRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{14}
}

func (x *SearchPostListRequest) GetOption() *post.Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *SearchPostListRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SearchPostListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchPostListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*post.Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SearchPostListResponse) Reset() {
	*x = SearchPostListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostListResponse) ProtoMessage() {}

func (x *SearchPostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostListResponse.ProtoReflect.Descriptor instead.
func (*SearchPostListResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{15}
}

func (x *SearchPostListResponse) GetData() []*post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type IncrementLikeCntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *IncrementLikeCntRequest) Reset() {
	*x = IncrementLikeCntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementLikeCntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementLikeCntRequest) ProtoMessage() {}

func (x *IncrementLikeCntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementLikeCntRequest.ProtoReflect.Descriptor instead.
func (*IncrementLikeCntRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{16}
}

func (x *IncrementLikeCntRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncrementLikeCntRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type IncrementLikeCntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncrementLikeCntResponse) Reset() {
	*x = IncrementLikeCntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementLikeCntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementLikeCntResponse) ProtoMessage() {}

func (x *IncrementLikeCntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementLikeCntResponse.ProtoReflect.Descriptor instead.
func (*IncrementLikeCntResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{17}
}

type DecrementLikeCntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DecrementLikeCntRequest) Reset() {
	*x = DecrementLikeCntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecrementLikeCntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementLikeCntRequest) ProtoMessage() {}

func (x *DecrementLikeCntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementLikeCntRequest.ProtoReflect.Descriptor instead.
func (*DecrementLikeCntRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{18}
}

func (x *DecrementLikeCntRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecrementLikeCntRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DecrementLikeCntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DecrementLikeCntResponse) Reset() {
	*x = DecrementLikeCntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecrementLikeCntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementLikeCntResponse) ProtoMessage() {}

func (x *DecrementLikeCntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementLikeCntResponse.ProtoReflect.Descriptor instead.
func (*DecrementLikeCntResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{19}
}

var File_proto_service_message_post_proto protoreflect.FileDescriptor

var file_proto_service_message_post_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x76, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x14, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x32, 0x2e,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x14, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a, 0x13, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a,
	0x17, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x32, 0x2e,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x17,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x42, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x17, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x17, 0x44, 0x65, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x74, 0x63, 0x30, 0x33, 0x30, 0x31, 0x32, 0x2f, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_service_message_post_proto_rawDescOnce sync.Once
	file_proto_service_message_post_proto_rawDescData = file_proto_service_message_post_proto_rawDesc
)

func file_proto_service_message_post_proto_rawDescGZIP() []byte {
	file_proto_service_message_post_proto_rawDescOnce.Do(func() {
		file_proto_service_message_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_message_post_proto_rawDescData)
	})
	return file_proto_service_message_post_proto_rawDescData
}

var file_proto_service_message_post_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_service_message_post_proto_goTypes = []interface{}{
	(*UploadPostRequest)(nil),        // 0: v2.service.message.UploadPostRequest
	(*UploadPostResponse)(nil),       // 1: v2.service.message.UploadPostResponse
	(*FetchPostListRequest)(nil),     // 2: v2.service.message.FetchPostListRequest
	(*FetchPostListResponse)(nil),    // 3: v2.service.message.FetchPostListResponse
	(*FetchPostRequest)(nil),         // 4: v2.service.message.FetchPostRequest
	(*FetchPostResponse)(nil),        // 5: v2.service.message.FetchPostResponse
	(*IncrementViewRequest)(nil),     // 6: v2.service.message.IncrementViewRequest
	(*IncrementViewResponse)(nil),    // 7: v2.service.message.IncrementViewResponse
	(*LeaveCommentRequest)(nil),      // 8: v2.service.message.LeaveCommentRequest
	(*LeaveCommentResponse)(nil),     // 9: v2.service.message.LeaveCommentResponse
	(*FetchCommentListRequest)(nil),  // 10: v2.service.message.FetchCommentListRequest
	(*FetchCommentListResponse)(nil), // 11: v2.service.message.FetchCommentListResponse
	(*DeleteCommentRequest)(nil),     // 12: v2.service.message.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),    // 13: v2.service.message.DeleteCommentResponse
	(*SearchPostListRequest)(nil),    // 14: v2.service.message.SearchPostListRequest
	(*SearchPostListResponse)(nil),   // 15: v2.service.message.SearchPostListResponse
	(*IncrementLikeCntRequest)(nil),  // 16: v2.service.message.IncrementLikeCntRequest
	(*IncrementLikeCntResponse)(nil), // 17: v2.service.message.IncrementLikeCntResponse
	(*DecrementLikeCntRequest)(nil),  // 18: v2.service.message.DecrementLikeCntRequest
	(*DecrementLikeCntResponse)(nil), // 19: v2.service.message.DecrementLikeCntResponse
	(*post.Data)(nil),                // 20: v2.entity.post.data
	(*post.Comment)(nil),             // 21: v2.entity.post.comment
	(*post.Option)(nil),              // 22: v2.entity.post.option
}
var file_proto_service_message_post_proto_depIdxs = []int32{
	20, // 0: v2.service.message.UploadPostRequest.data:type_name -> v2.entity.post.data
	20, // 1: v2.service.message.FetchPostListResponse.data:type_name -> v2.entity.post.data
	20, // 2: v2.service.message.FetchPostResponse.data:type_name -> v2.entity.post.data
	21, // 3: v2.service.message.LeaveCommentRequest.comment:type_name -> v2.entity.post.comment
	21, // 4: v2.service.message.FetchCommentListResponse.comment_list:type_name -> v2.entity.post.comment
	22, // 5: v2.service.message.SearchPostListRequest.option:type_name -> v2.entity.post.option
	20, // 6: v2.service.message.SearchPostListResponse.data:type_name -> v2.entity.post.data
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_service_message_post_proto_init() }
func file_proto_service_message_post_proto_init() {
	if File_proto_service_message_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service_message_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchCommentListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchCommentListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPostListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPostListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementLikeCntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementLikeCntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecrementLikeCntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecrementLikeCntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_message_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_service_message_post_proto_goTypes,
		DependencyIndexes: file_proto_service_message_post_proto_depIdxs,
		MessageInfos:      file_proto_service_message_post_proto_msgTypes,
	}.Build()
	File_proto_service_message_post_proto = out.File
	file_proto_service_message_post_proto_rawDesc = nil
	file_proto_service_message_post_proto_goTypes = nil
	file_proto_service_message_post_proto_depIdxs = nil
}
