// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/service/message/post.proto

package message

import (
	post "github.com/dtc03012/me/protobuf/proto/entity/post"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *post.Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadPostRequest) Reset() {
	*x = UploadPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostRequest) ProtoMessage() {}

func (x *UploadPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostRequest.ProtoReflect.Descriptor instead.
func (*UploadPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{0}
}

func (x *UploadPostRequest) GetData() *post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadPostResponse) Reset() {
	*x = UploadPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPostResponse) ProtoMessage() {}

func (x *UploadPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPostResponse.ProtoReflect.Descriptor instead.
func (*UploadPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{1}
}

type FetchPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row  int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FetchPostsRequest) Reset() {
	*x = FetchPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostsRequest) ProtoMessage() {}

func (x *FetchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostsRequest.ProtoReflect.Descriptor instead.
func (*FetchPostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{2}
}

func (x *FetchPostsRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *FetchPostsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FetchPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*post.Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchPostsResponse) Reset() {
	*x = FetchPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_message_post_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPostsResponse) ProtoMessage() {}

func (x *FetchPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_message_post_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPostsResponse.ProtoReflect.Descriptor instead.
func (*FetchPostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_message_post_proto_rawDescGZIP(), []int{3}
}

func (x *FetchPostsResponse) GetData() []*post.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_service_message_post_proto protoreflect.FileDescriptor

var file_proto_service_message_post_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x76, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x11, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x74, 0x63, 0x30, 0x33, 0x30, 0x31, 0x32, 0x2f, 0x6d, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_service_message_post_proto_rawDescOnce sync.Once
	file_proto_service_message_post_proto_rawDescData = file_proto_service_message_post_proto_rawDesc
)

func file_proto_service_message_post_proto_rawDescGZIP() []byte {
	file_proto_service_message_post_proto_rawDescOnce.Do(func() {
		file_proto_service_message_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_message_post_proto_rawDescData)
	})
	return file_proto_service_message_post_proto_rawDescData
}

var file_proto_service_message_post_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_service_message_post_proto_goTypes = []interface{}{
	(*UploadPostRequest)(nil),  // 0: v2.service.message.UploadPostRequest
	(*UploadPostResponse)(nil), // 1: v2.service.message.UploadPostResponse
	(*FetchPostsRequest)(nil),  // 2: v2.service.message.FetchPostsRequest
	(*FetchPostsResponse)(nil), // 3: v2.service.message.FetchPostsResponse
	(*post.Data)(nil),          // 4: v2.entity.post.data
}
var file_proto_service_message_post_proto_depIdxs = []int32{
	4, // 0: v2.service.message.UploadPostRequest.data:type_name -> v2.entity.post.data
	4, // 1: v2.service.message.FetchPostsResponse.data:type_name -> v2.entity.post.data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_service_message_post_proto_init() }
func file_proto_service_message_post_proto_init() {
	if File_proto_service_message_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service_message_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_message_post_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_message_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_service_message_post_proto_goTypes,
		DependencyIndexes: file_proto_service_message_post_proto_depIdxs,
		MessageInfos:      file_proto_service_message_post_proto_msgTypes,
	}.Build()
	File_proto_service_message_post_proto = out.File
	file_proto_service_message_post_proto_rawDesc = nil
	file_proto_service_message_post_proto_goTypes = nil
	file_proto_service_message_post_proto_depIdxs = nil
}
