// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	option "github.com/dtc03012/me/db/option"
	mock "github.com/stretchr/testify/mock"

	post "github.com/dtc03012/me/protobuf/proto/entity/post"

	sql "database/sql"

	sqlx "github.com/jmoiron/sqlx"
)

// DBService is an autogenerated mock type for the DBService type
type DBService struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *DBService) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sqlx.Tx, error) {
	ret := _m.Called(ctx, opts)

	var r0 *sqlx.Tx
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sqlx.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckAdminPassword provides a mock function with given fields: ctx, tx, password
func (_m *DBService) CheckAdminPassword(ctx context.Context, tx *sqlx.Tx, password string) (bool, error) {
	ret := _m.Called(ctx, tx, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) bool); ok {
		r0 = rf(ctx, tx, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckCommentPassword provides a mock function with given fields: ctx, tx, cid, password
func (_m *DBService) CheckCommentPassword(ctx context.Context, tx *sqlx.Tx, cid int, password string) (bool, error) {
	ret := _m.Called(ctx, tx, cid, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) bool); ok {
		r0 = rf(ctx, tx, cid, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r1 = rf(ctx, tx, cid, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPostPassword provides a mock function with given fields: ctx, tx, pid, password
func (_m *DBService) CheckPostPassword(ctx context.Context, tx *sqlx.Tx, pid int, password string) (bool, error) {
	ret := _m.Called(ctx, tx, pid, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) bool); ok {
		r0 = rf(ctx, tx, pid, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r1 = rf(ctx, tx, pid, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckUserLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *DBService) CheckUserLike(ctx context.Context, tx *sqlx.Tx, pid int, uuid string) (bool, error) {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) bool); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r1 = rf(ctx, tx, pid, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecrementLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *DBService) DecrementLike(ctx context.Context, tx *sqlx.Tx, pid int, uuid string) error {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, tx, commentId, password
func (_m *DBService) DeleteComment(ctx context.Context, tx *sqlx.Tx, commentId int, password string) error {
	ret := _m.Called(ctx, tx, commentId, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r0 = rf(ctx, tx, commentId, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: ctx, tx, postId
func (_m *DBService) DeletePost(ctx context.Context, tx *sqlx.Tx, postId int) error {
	ret := _m.Called(ctx, tx, postId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) error); ok {
		r0 = rf(ctx, tx, postId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchComment provides a mock function with given fields: ctx, tx, cid
func (_m *DBService) FetchComment(ctx context.Context, tx *sqlx.Tx, cid int) (*post.Comment, error) {
	ret := _m.Called(ctx, tx, cid)

	var r0 *post.Comment
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) *post.Comment); ok {
		r0 = rf(ctx, tx, cid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, cid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchCommentList provides a mock function with given fields: ctx, tx, opt
func (_m *DBService) FetchCommentList(ctx context.Context, tx *sqlx.Tx, opt *option.CommentOption) ([]*post.Comment, error) {
	ret := _m.Called(ctx, tx, opt)

	var r0 []*post.Comment
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *option.CommentOption) []*post.Comment); ok {
		r0 = rf(ctx, tx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *option.CommentOption) error); ok {
		r1 = rf(ctx, tx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchPost provides a mock function with given fields: ctx, tx, postId
func (_m *DBService) FetchPost(ctx context.Context, tx *sqlx.Tx, postId int) (*post.Data, error) {
	ret := _m.Called(ctx, tx, postId)

	var r0 *post.Data
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) *post.Data); ok {
		r0 = rf(ctx, tx, postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchPostList provides a mock function with given fields: ctx, tx, opt
func (_m *DBService) FetchPostList(ctx context.Context, tx *sqlx.Tx, opt *option.PostOption) ([]*post.Data, error) {
	ret := _m.Called(ctx, tx, opt)

	var r0 []*post.Data
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *option.PostOption) []*post.Data); ok {
		r0 = rf(ctx, tx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *option.PostOption) error); ok {
		r1 = rf(ctx, tx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAdminUUID provides a mock function with given fields: ctx, tx, uuid
func (_m *DBService) FindAdminUUID(ctx context.Context, tx *sqlx.Tx, uuid string) (bool, error) {
	ret := _m.Called(ctx, tx, uuid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) bool); ok {
		r0 = rf(ctx, tx, uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalCommentCount provides a mock function with given fields: ctx, tx, pid
func (_m *DBService) GetTotalCommentCount(ctx context.Context, tx *sqlx.Tx, pid int) (int32, error) {
	ret := _m.Called(ctx, tx, pid)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) int32); ok {
		r0 = rf(ctx, tx, pid)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, pid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPostCount provides a mock function with given fields: ctx, tx, opt
func (_m *DBService) GetTotalPostCount(ctx context.Context, tx *sqlx.Tx, opt *option.PostOption) (int32, error) {
	ret := _m.Called(ctx, tx, opt)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *option.PostOption) int32); ok {
		r0 = rf(ctx, tx, opt)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *option.PostOption) error); ok {
		r1 = rf(ctx, tx, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementLike provides a mock function with given fields: ctx, tx, pid, uuid
func (_m *DBService) IncrementLike(ctx context.Context, tx *sqlx.Tx, pid int, uuid string) error {
	ret := _m.Called(ctx, tx, pid, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r0 = rf(ctx, tx, pid, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrementViews provides a mock function with given fields: ctx, tx, postId, uuid
func (_m *DBService) IncrementViews(ctx context.Context, tx *sqlx.Tx, postId int, uuid string) error {
	ret := _m.Called(ctx, tx, postId, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, string) error); ok {
		r0 = rf(ctx, tx, postId, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertAdminUUID provides a mock function with given fields: ctx, tx, uuid
func (_m *DBService) InsertAdminUUID(ctx context.Context, tx *sqlx.Tx, uuid string) error {
	ret := _m.Called(ctx, tx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) error); ok {
		r0 = rf(ctx, tx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveComment provides a mock function with given fields: ctx, tx, comment
func (_m *DBService) LeaveComment(ctx context.Context, tx *sqlx.Tx, comment *post.Comment) error {
	ret := _m.Called(ctx, tx, comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *post.Comment) error); ok {
		r0 = rf(ctx, tx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePost provides a mock function with given fields: ctx, tx, postData
func (_m *DBService) UpdatePost(ctx context.Context, tx *sqlx.Tx, postData *post.Data) error {
	ret := _m.Called(ctx, tx, postData)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *post.Data) error); ok {
		r0 = rf(ctx, tx, postData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadPost provides a mock function with given fields: ctx, tx, postData
func (_m *DBService) UploadPost(ctx context.Context, tx *sqlx.Tx, postData *post.Data) error {
	ret := _m.Called(ctx, tx, postData)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *post.Data) error); ok {
		r0 = rf(ctx, tx, postData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDBService interface {
	mock.TestingT
	Cleanup(func())
}

// NewDBService creates a new instance of DBService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDBService(t mockConstructorTestingTNewDBService) *DBService {
	mock := &DBService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
