// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/entity/widget/weather.proto

package widget

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherCondition int32

const (
	Weather_NONE     WeatherCondition = 0
	Weather_SUNNY    WeatherCondition = 1
	Weather_CLOUDY   WeatherCondition = 2
	Weather_OVERCAST WeatherCondition = 3
)

// Enum value maps for WeatherCondition.
var (
	WeatherCondition_name = map[int32]string{
		0: "NONE",
		1: "SUNNY",
		2: "CLOUDY",
		3: "OVERCAST",
	}
	WeatherCondition_value = map[string]int32{
		"NONE":     0,
		"SUNNY":    1,
		"CLOUDY":   2,
		"OVERCAST": 3,
	}
)

func (x WeatherCondition) Enum() *WeatherCondition {
	p := new(WeatherCondition)
	*p = x
	return p
}

func (x WeatherCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeatherCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_widget_weather_proto_enumTypes[0].Descriptor()
}

func (WeatherCondition) Type() protoreflect.EnumType {
	return &file_proto_entity_widget_weather_proto_enumTypes[0]
}

func (x WeatherCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeatherCondition.Descriptor instead.
func (WeatherCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_widget_weather_proto_rawDescGZIP(), []int{1, 0}
}

type PrecipitationCondition int32

const (
	Precipitation_NONE       PrecipitationCondition = 0
	Precipitation_RAINY      PrecipitationCondition = 1
	Precipitation_RAINY_SNOW PrecipitationCondition = 2
	Precipitation_SNOW       PrecipitationCondition = 3
	Precipitation_SHOWER     PrecipitationCondition = 4
)

// Enum value maps for PrecipitationCondition.
var (
	PrecipitationCondition_name = map[int32]string{
		0: "NONE",
		1: "RAINY",
		2: "RAINY_SNOW",
		3: "SNOW",
		4: "SHOWER",
	}
	PrecipitationCondition_value = map[string]int32{
		"NONE":       0,
		"RAINY":      1,
		"RAINY_SNOW": 2,
		"SNOW":       3,
		"SHOWER":     4,
	}
)

func (x PrecipitationCondition) Enum() *PrecipitationCondition {
	p := new(PrecipitationCondition)
	*p = x
	return p
}

func (x PrecipitationCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrecipitationCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_widget_weather_proto_enumTypes[1].Descriptor()
}

func (PrecipitationCondition) Type() protoreflect.EnumType {
	return &file_proto_entity_widget_weather_proto_enumTypes[1]
}

func (x PrecipitationCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrecipitationCondition.Descriptor instead.
func (PrecipitationCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_widget_weather_proto_rawDescGZIP(), []int{2, 0}
}

type Temperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Now     string `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	Highest string `protobuf:"bytes,2,opt,name=highest,proto3" json:"highest,omitempty"`
	Lowest  string `protobuf:"bytes,3,opt,name=lowest,proto3" json:"lowest,omitempty"`
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entity_widget_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_widget_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_proto_entity_widget_weather_proto_rawDescGZIP(), []int{0}
}

func (x *Temperature) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *Temperature) GetHighest() string {
	if x != nil {
		return x.Highest
	}
	return ""
}

func (x *Temperature) GetLowest() string {
	if x != nil {
		return x.Lowest
	}
	return ""
}

type Weather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeatherCondition WeatherCondition `protobuf:"varint,1,opt,name=weather_condition,json=weatherCondition,proto3,enum=v2.entity.widget.WeatherCondition" json:"weather_condition,omitempty"`
}

func (x *Weather) Reset() {
	*x = Weather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entity_widget_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_widget_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_proto_entity_widget_weather_proto_rawDescGZIP(), []int{1}
}

func (x *Weather) GetWeatherCondition() WeatherCondition {
	if x != nil {
		return x.WeatherCondition
	}
	return Weather_NONE
}

type Precipitation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrecipitationCondition PrecipitationCondition `protobuf:"varint,1,opt,name=precipitation_condition,json=precipitationCondition,proto3,enum=v2.entity.widget.PrecipitationCondition" json:"precipitation_condition,omitempty"`
}

func (x *Precipitation) Reset() {
	*x = Precipitation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_entity_widget_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Precipitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precipitation) ProtoMessage() {}

func (x *Precipitation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_widget_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precipitation.ProtoReflect.Descriptor instead.
func (*Precipitation) Descriptor() ([]byte, []int) {
	return file_proto_entity_widget_weather_proto_rawDescGZIP(), []int{2}
}

func (x *Precipitation) GetPrecipitationCondition() PrecipitationCondition {
	if x != nil {
		return x.PrecipitationCondition
	}
	return Precipitation_NONE
}

var File_proto_entity_widget_weather_proto protoreflect.FileDescriptor

var file_proto_entity_widget_weather_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x22, 0x51, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x07, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x11, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x23, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x77, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x55, 0x4e, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f, 0x55,
	0x44, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x56, 0x45, 0x52, 0x43, 0x41, 0x53, 0x54,
	0x10, 0x03, 0x22, 0xbb, 0x01, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x62, 0x0a, 0x17, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x76, 0x32, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x16, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x52, 0x41, 0x49, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41,
	0x49, 0x4e, 0x59, 0x5f, 0x53, 0x4e, 0x4f, 0x57, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4e,
	0x4f, 0x57, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x04,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x74, 0x63, 0x30, 0x33, 0x30, 0x31, 0x32, 0x2f, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_entity_widget_weather_proto_rawDescOnce sync.Once
	file_proto_entity_widget_weather_proto_rawDescData = file_proto_entity_widget_weather_proto_rawDesc
)

func file_proto_entity_widget_weather_proto_rawDescGZIP() []byte {
	file_proto_entity_widget_weather_proto_rawDescOnce.Do(func() {
		file_proto_entity_widget_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_entity_widget_weather_proto_rawDescData)
	})
	return file_proto_entity_widget_weather_proto_rawDescData
}

var file_proto_entity_widget_weather_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_entity_widget_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_entity_widget_weather_proto_goTypes = []interface{}{
	(WeatherCondition)(0),       // 0: v2.entity.widget.weather.condition
	(PrecipitationCondition)(0), // 1: v2.entity.widget.precipitation.condition
	(*Temperature)(nil),         // 2: v2.entity.widget.temperature
	(*Weather)(nil),             // 3: v2.entity.widget.weather
	(*Precipitation)(nil),       // 4: v2.entity.widget.precipitation
}
var file_proto_entity_widget_weather_proto_depIdxs = []int32{
	0, // 0: v2.entity.widget.weather.weather_condition:type_name -> v2.entity.widget.weather.condition
	1, // 1: v2.entity.widget.precipitation.precipitation_condition:type_name -> v2.entity.widget.precipitation.condition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_entity_widget_weather_proto_init() }
func file_proto_entity_widget_weather_proto_init() {
	if File_proto_entity_widget_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_entity_widget_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_entity_widget_weather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_entity_widget_weather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Precipitation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_entity_widget_weather_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_entity_widget_weather_proto_goTypes,
		DependencyIndexes: file_proto_entity_widget_weather_proto_depIdxs,
		EnumInfos:         file_proto_entity_widget_weather_proto_enumTypes,
		MessageInfos:      file_proto_entity_widget_weather_proto_msgTypes,
	}.Build()
	File_proto_entity_widget_weather_proto = out.File
	file_proto_entity_widget_weather_proto_rawDesc = nil
	file_proto_entity_widget_weather_proto_goTypes = nil
	file_proto_entity_widget_weather_proto_depIdxs = nil
}
